[package]
name = "ogma-strings"
description = "Translation catalogue analysis for Ogma"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
ogma-model.workspace = true
ogma-discovery.workspace = true
ogma-locale.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
